/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dto.ProductoDTO;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import dao.ProductoFDAO;

/**
 *
 * @author 7053
 */
public class ProductoView extends javax.swing.JFrame {
    private ProductoDTO dto;
    private ProductoFDAO dao;
    /**
     * Creates new form ProductoView
     */
    public ProductoView() {
        try {
            initComponents();
            dao=new ProductoFDAO();
        } catch (IOException ex) {
            Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, " NO SE ENCUENTRA EL ARCHIVO "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMotherboard = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaListado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtCPU = new javax.swing.JTextField();
        txtGPU = new javax.swing.JTextField();
        txtRAM = new javax.swing.JTextField();
        txtMonitores = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtPSU = new javax.swing.JTextField();
        txtGabinete = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jTextField3.setText("jTextField3");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 420, 800));
        setMinimumSize(new java.awt.Dimension(420, 440));
        setPreferredSize(new java.awt.Dimension(500, 800));
        getContentPane().setLayout(null);

        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 90, 20);

        txtMotherboard.setColumns(3);
        txtMotherboard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMotherboardKeyTyped(evt);
            }
        });
        getContentPane().add(txtMotherboard);
        txtMotherboard.setBounds(120, 120, 170, 25);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar);
        btnInsertar.setBounds(310, 40, 80, 29);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(310, 80, 80, 29);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(310, 120, 80, 29);

        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(310, 160, 80, 29);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(310, 200, 80, 29);

        txaListado.setColumns(20);
        txaListado.setRows(5);
        jScrollPane1.setViewportView(txaListado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 410, 370, 180);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 240, 80, 29);

        txtId.setColumns(3);
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(120, 40, 170, 25);

        txtCPU.setColumns(3);
        txtCPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPUKeyTyped(evt);
            }
        });
        getContentPane().add(txtCPU);
        txtCPU.setBounds(120, 80, 170, 25);

        txtGPU.setColumns(3);
        txtGPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGPUKeyTyped(evt);
            }
        });
        getContentPane().add(txtGPU);
        txtGPU.setBounds(120, 200, 170, 25);

        txtRAM.setColumns(3);
        txtRAM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRAMKeyTyped(evt);
            }
        });
        getContentPane().add(txtRAM);
        txtRAM.setBounds(120, 160, 170, 25);

        txtMonitores.setColumns(3);
        txtMonitores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMonitoresKeyTyped(evt);
            }
        });
        getContentPane().add(txtMonitores);
        txtMonitores.setBounds(120, 320, 170, 25);

        txtPrecio.setColumns(3);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(120, 360, 170, 25);

        txtPSU.setColumns(3);
        txtPSU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPSUKeyTyped(evt);
            }
        });
        getContentPane().add(txtPSU);
        txtPSU.setBounds(120, 240, 170, 25);

        txtGabinete.setColumns(3);
        txtGabinete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGabineteKeyTyped(evt);
            }
        });
        getContentPane().add(txtGabinete);
        txtGabinete.setBounds(120, 280, 170, 25);

        jLabel6.setText("tamaño");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 90, 20);

        jLabel7.setText("CPU");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 80, 90, 20);

        jLabel8.setText("Motherboard");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 120, 90, 20);

        jLabel9.setText("RAM (gb) ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 160, 90, 20);

        jLabel10.setText("GPU");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 200, 90, 20);

        jLabel11.setText("PSU (watts)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 240, 90, 20);

        jLabel12.setText("Gabinete");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 280, 90, 20);

        jLabel13.setText("# Monitores");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 320, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (!txtId.getText().isEmpty() && !txtCPU.getText().isEmpty() && !txtMotherboard.getText().isEmpty() && !txtRAM.getText().isEmpty() && !txtGPU.getText().isEmpty() && !txtPSU.getText().isEmpty() && !txtGabinete.getText().isEmpty() && !txtMonitores.getText().isEmpty() && !txtPrecio.getText().isEmpty()) {
            dto=new ProductoDTO();
            dto.setId(Long.parseLong(txtId.getText()));
            dto.setCpu(new StringBuffer(txtCPU.getText()));
            dto.setMotherboard(new StringBuffer(txtMotherboard.getText()));
            dto.setRam(Integer.parseInt(txtRAM.getText()));
            dto.setGpu(new StringBuffer(txtGPU.getText()));
            dto.setPsu(Integer.parseInt(txtPSU.getText()));
            dto.setGabinete(new StringBuffer(txtGabinete.getText()));
            dto.setMonitores(Integer.parseInt(txtMonitores.getText()));
            dto.setPrecio(Integer.parseInt(txtPrecio.getText()));
        
            try {
                if(dao.agregar(dto)){
                    JOptionPane.showMessageDialog(this, " INSERTADO ");
                }else{
                    JOptionPane.showMessageDialog(this, " NO SE PUDO INSERTAR ");
                }
            } catch (IOException ex) {
                Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llena todos los campos");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String Id=JOptionPane.showInputDialog(" Id a buscar ");
        if ((Id != null) && (Id.length() > 0)) {
        dto=new ProductoDTO();
        dto.setId(Long.parseLong(Id));
        try {
            dto=dao.obtenerPorId(dto);
            if(dto==null){
                JOptionPane.showMessageDialog(this, " NO SE ENCONTRO ");
            }else{
                txtId.setText(String.valueOf(dto.getId()));
                txtMotherboard.setText(String.valueOf(dto.getId()));
                txtCPU.setText(dto.getCpu().toString());
                txtMotherboard.setText(dto.getMotherboard().toString());
                txtRAM.setText(String.valueOf(dto.getRam()));
                txtGPU.setText(dto.getGpu().toString());
                txtPSU.setText(String.valueOf(dto.getPsu()));
                txtGabinete.setText(dto.getGabinete().toString());
                txtMonitores.setText(String.valueOf(dto.getMonitores()));
                txtPrecio.setText(String.valueOf(dto.getPrecio()));
            }
        } catch (IOException ex) {
            Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
//        dto=new ProductoDTO();
                if (!txtId.getText().isEmpty() && !txtCPU.getText().isEmpty() && !txtMotherboard.getText().isEmpty() && !txtRAM.getText().isEmpty() && !txtGPU.getText().isEmpty() && !txtPSU.getText().isEmpty() && !txtGabinete.getText().isEmpty() && !txtMonitores.getText().isEmpty() && !txtPrecio.getText().isEmpty()) {
                     try {
                        if(dao.actualizar(dto)){
                            JOptionPane.showMessageDialog(this, " EDITADO ");
                        }else{
                            JOptionPane.showMessageDialog(this, " NO SE PUDO EDITAR ");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Llena todos los datos");
                }
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
                        if (!txtId.getText().isEmpty() && !txtCPU.getText().isEmpty() && !txtMotherboard.getText().isEmpty() && !txtRAM.getText().isEmpty() && !txtGPU.getText().isEmpty() && !txtPSU.getText().isEmpty() && !txtGabinete.getText().isEmpty() && !txtMonitores.getText().isEmpty() && !txtPrecio.getText().isEmpty()) {

        dto=new ProductoDTO();
        try {
            if(dao.eliminar(dto)){
                JOptionPane.showMessageDialog(this, " BORRADO ");
            }else{
                JOptionPane.showMessageDialog(this, " NO SE PUDO BORRAR ");
            }
        } catch (IOException ex) {
            Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
        }
} else {
                    JOptionPane.showMessageDialog(null, "Llena todos los datos");
                }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try {
            List<ProductoDTO> lista=dao.obtenerTodos();
            if(lista==null || lista.isEmpty()){
                JOptionPane.showMessageDialog(this, " NO SE ENCONTRO ");
            }else{
                txaListado.setText(lista.toString());
//                txtId.setText(String.valueOf(dto.getId()));
//                txtNombre.setText(dto.getNombre());
//                txtPrecio.setText(String.valueOf(dto.getPrecio()));
//                txtExistencia.setText(String.valueOf(dto.getExistencia()));
            }
        } catch (IOException ex) {
            Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProductoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtId.setText("");
        txtCPU.setText("");
        txtMotherboard.setText("");
        txtRAM.setText("");
        txtGPU.setText("");
        txtPSU.setText("");
        txtGabinete.setText("");
        txtMonitores.setText("");
        txtPrecio.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        if (txtId.getText().length() >= 3 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtCPUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPUKeyTyped
         if (txtCPU.getText().length() >= 15 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtCPUKeyTyped

    private void txtMotherboardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotherboardKeyTyped
         if (txtMotherboard.getText().length() >= 20 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtMotherboardKeyTyped

    private void txtRAMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRAMKeyTyped
        if (txtRAM.getText().length() >= 3 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtRAMKeyTyped

    private void txtGPUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGPUKeyTyped
        if (txtGPU.getText().length() >= 20 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtGPUKeyTyped

    private void txtPSUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPSUKeyTyped
        if (txtPSU.getText().length() >= 4 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtPSUKeyTyped

    private void txtGabineteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGabineteKeyTyped
        if (txtGabinete.getText().length() >= 20 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtGabineteKeyTyped

    private void txtMonitoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMonitoresKeyTyped
        if (txtMonitores.getText().length() >= 1 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtMonitoresKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        if (txtPrecio.getText().length() >= 2 ) 
            evt.consume(); 
    }//GEN-LAST:event_txtPrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea txaListado;
    private javax.swing.JTextField txtCPU;
    private javax.swing.JTextField txtGPU;
    private javax.swing.JTextField txtGabinete;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMonitores;
    private javax.swing.JTextField txtMotherboard;
    private javax.swing.JTextField txtPSU;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRAM;
    // End of variables declaration//GEN-END:variables
}
